// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJLvwiX8p4MhXECrwjYkNj-3bjz_-ws0k',
    appId: '1:1062872438604:web:9d654fd276b9d4158521e9',
    messagingSenderId: '1062872438604',
    projectId: 'eshop-pos',
    authDomain: 'eshop-pos.firebaseapp.com',
    storageBucket: 'eshop-pos.firebasestorage.app',
    measurementId: 'G-HBJLH7Q3CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyRfRBA6T2pH5I1Z3zG-8e6XWnWB5Ci8A',
    appId: '1:1062872438604:android:1367030756caead78521e9',
    messagingSenderId: '1062872438604',
    projectId: 'eshop-pos',
    storageBucket: 'eshop-pos.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJLvwiX8p4MhXECrwjYkNj-3bjz_-ws0k',
    appId: '1:1062872438604:web:7953970b49f492098521e9',
    messagingSenderId: '1062872438604',
    projectId: 'eshop-pos',
    authDomain: 'eshop-pos.firebaseapp.com',
    storageBucket: 'eshop-pos.firebasestorage.app',
    measurementId: 'G-KP4NCDECKL',
  );
}
